[ui]
scale = 1.0
font = "Monofur Nerd Font Mono"
alpha = 0.9
theme = "system"

[paths]
cache = "cache.json"

[plugin]
ocr_path = '..\TextCap-Daemon\TextCap-Daemon.exe'
use_ocr = true

[backend]
model_name = "gemma4"

init_msg = "Hi! I'm playing a text heavy game in Japanese, its original language. Would you be able to help with translating some dialogues and instructions into English for me? The text will be extracted via OCR, so ask me to verify if you find potential errors. Otherwise, please limit your response contents to the following 3 sections unless I ask any follow-up questions in English: 1. [Must Include] a few English translation options (especially when you suspect colloquialism and set phrases, for which please provide some explanations), 2. [Must Include] a lexical breakdown of the original text including romaji representations and explanations, and 3. [Optional] a glossary of 2 or fewer note on grammar or style of speach, all in bullet point form. Do not include any other additional note. Do not include any non-basic markdown formatting (including latex) either. Thank you!\n\n"

use_init_res = false

init_res = "Understood. I will limit my response to exactly these three sections:\n\n1. A few English translation option\n2. A lexical breakdown of the original text including romanji representations\n3. A glossary of 2 or fewer grammatical/cultural notes (focusing on word forms)\n\nI will also always prompt you to verify the text if it appears corrupted due to OCR, and otherwise proceed directly with the structure above without any extra notes.\n\nPlease provide the Japanese text when you are ready.\n\n"